### PR TITLE
Add openBrowser flag for playground cmd

### PR DESCRIPTION
**Pull request by pokorson**

### CODE REVIEW

**Comment by kbrandwijk** [comment]
Can you give it an alias, and maybe shorter it to just `--open`|`-o`?

**Comment by pokorson** [comment]
@kbrandwijk sure

**Comment by pokorson** [comment]
@kbrandwijk @schickling proposed `server-only` name for a param, I'm thinking if `--open` isn't to short ? It doesn't say much

**Comment by schickling** [comment]
Any reason why you didn't go for `--server-only`? Imo it's a better "inverse" to opening the browser/electron app.

**Comment by pokorson** [comment]
@schickling do you see any alias for this name?

**Comment by kbrandwijk** [comment]
`yargs` supports a pattern of a `--no-` prefix for boolean parameters, so let's come up with something that has both the right default behavior, and works well with this pattern.

**Comment by pokorson** [comment]
I can't think of any good name starting with `--no-` for this argument. So far I like `--server-only` the most

**Comment by schickling** [comment]
Same here. Can you adjust your PR?

**Comment by pokorson** [comment]
@schickling I will

**Comment by pokorson** [comment]
@schickling I've updated arg name

**Comment by schickling** [comment]
Thanks a lot, @pokorson. I think you're also missing adjustments in the code path for the electron app. Would be great if you could adjust that.

**Pull request merged**
